### ISSUE TITLE
第7页 3A4000 片内集成2个64位的内存控制器

### ISSUE THREAD

**Issue by Michael0066** [chenhuacai/ulek#4]
第7页 片内集成2个64位 800MHz的内存控制器 ， 龙芯官网 3a4000 的描述为： 2个72位DDR4-2400控制器，支持ECC校验http://www.loongson.cn/product/cpu/3/1288.html

**Comment by chenhuacai** [comment]
严格来说这个不算BUG，因为龙芯3A4000的手册说的也是64位。72位指的是64位数据通道+8位ECC校验。如果本书重印，此处会加一条注释，谢谢。

**Comment by chenhuacai** [comment]
严格来说这个不算BUG，因为龙芯3A4000的手册说的也是64位。72位指的是64位数据通道+8位ECC校验。如果本书重印，此处会加一条注释，谢谢。

**Comment by Michael0066** [comment]
不懂就问 ，DDR4-2400  是不是对应为 1200MHz 内存控制器

**Comment by chenhuacai** [comment]
是，但是处理器手册写的是800MHz，所以，此处到底以哪个为准我也不确定了，个人倾向于认为1200MHz是对的。

**Comment by Michael0066** [comment]
好的，谢谢解答

**Comment by xied75** [comment]
2400不一定对应1200，在过去有FSB概念的时候，牵扯倍频，前端总线FSB是800MHz，则二倍频为1600，三倍频就是2400。但现今北桥直接集成之后就不知道这个概念还适用否了。

**Comment by chenhuacai** [comment]
请问里可否愿意在勘误表上署真名？
