### ISSUE TITLE
3.3.2 中断处理的分派 - 排版错误

### ISSUE THREAD

**Issue by xied75** [chenhuacai/ulek#5]
抱歉是kindle版不知道纸页是多少，在倒数第二段落，`c0_compare_interrupt()`多次被打成`c0 com_pare_interrupt()`。这一段还有类似的其他错误。

**Comment by chenhuacai** [comment]
经确认，纸书上没问题，应该是电子书排自动版造成的。

**Comment by chenhuacai** [comment]
如无反馈就关闭啦。
